repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-added-large-files
        args: ['--maxkb=500']

-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.2
    hooks:
      - id: ruff-check
        args: [--fix, --show-fixes]

      - id: ruff-format
        alias: ruff-format-diff
        name: ruff-format (show diff)
        args: [--diff]
        verbose: true

      - id: ruff-format
        name: ruff-format (apply fixes)
